import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import SessionProvider from './providers/SessionProvider';
import { getServerSession } from 'next-auth';
import './globals.css';
import ContextProvider from './providers/ContextProvider';
import NextTopLoader from 'nextjs-toploader';
import { GlobalProvider } from './context/GlobalProvider';
import { authOptions } from './api/auth/[...nextauth]/route';

const nunito = Nunito({
    weight: ['400', '500', '600', '700', '800'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Todo App',
    description: 'Generated by create next app',
    icons: {
        icon: '/icon.png',
    },
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(authOptions);

    return (
        <html lang='en'>
            <head>
                <link
                    rel='stylesheet'
                    href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css'
                    integrity='sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=='
                    crossOrigin='anonymous'
                    referrerPolicy='no-referrer'
                />
            </head>
            <body className={nunito.className}>
                <NextTopLoader
                    height={2}
                    color='#27AE60'
                    easing='cubic-bezier(0.53,0.21,0,1)'
                />
                <SessionProvider session={session}>
                    <GlobalProvider>
                        <ContextProvider>{children}</ContextProvider>
                    </GlobalProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
